name: Translate README

on: [push]

jobs:
  translate:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Add this line

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Translate README
        uses: dephraiim/translate-readme@main
        with:
          LANG: "en" 
